### ISSUE TITLE
Sentence text type identification using FCGEC-Joint

### ISSUE THREAD

**Issue by kalixim** [xlxwalex/FCGEC#39]
Hello, I have finished  the error correction according to the steps you provided, but now I want to predict the error type identification for every text at the same time. Can I use FCGEC-Joint  and get the desired result  by changing some params? If so could you please give me an example?Thank you very much.

**Comment by xlxwalex** [comment]
Hi, 

The main code in our repository is for Error Correction task. Since for the two sub-tasks of error detection and error type identification, we only utilized the simplest pre-trained model with the fully connected layers for fine-tuning, we did not provide the code for this part directly in the repository. 

However, you can refer to the code for type identification in the `TaggerModelTT`I class of the [`tagger_model.py file`](https://github.com/xlxwalex/FCGEC/blob/5a43f232e89108181191e0400db44ac801d2258f/model/STG-correction/Model/tagger_model.py#L36).
